#!/usr/bin/env python

from __future__ import print_function
import subprocess
import json
from pprint import pprint

import argparse


def parse_arguments():
    global args, parser
    parser = argparse.ArgumentParser(description='Check kubernetes deployments validity')
    parser.add_argument('--namespace', dest='namespace',
                    help='Process only namespace (default: check all namespaces)')
    parser.add_argument('--name', dest='name', 
                    help='Process only deployment name')
    parser.add_argument('--ignore-deployments', dest='ignored_deployments',  
                    default='',
                    help='Ignore these deployments (kube-lego/kube-lego)')
    args = parser.parse_args()


def get_query_command():
    global args, parser

    if args.name and not args.namespace:
        print("ERROR: Providing name without namespace is forbidden\n")
        parser.print_help()
        raise SystemExit(3)

    if args.name:
        command = 'kubectl get deployments --namespace={} --field-selector=metadata.name={} -o json'.format(args.namespace, args.name)
    
    elif args.namespace:
        command = 'kubectl get deployments --namespace {} -o json'.format(args.namespace)
    else:
        command = 'kubectl get deployments --all-namespaces -o json'
    return command

def main():
    query_command = get_query_command()
    cmd = subprocess.check_output(query_command.split())
    data = json.loads(cmd)
    assert data['apiVersion'] in ('v1', 'extensions/v1beta1')

    totals = dict(
         requested=0, updated=0, missing=0, ready=0)
    broken_deployments = {}
    valid_deployments = {}

    ignored_deployments = args.ignored_deployments.split()

    for deployment in data['items']:
        name = deployment['metadata']['name']
        namespace = deployment['metadata']['namespace']
        full_name = '{}/{}'.format(namespace, name)
        # this should be ignored
        if full_name in ignored_deployments:
            continue

	# 
        valid_deployments[full_name] = 0

        if deployment['spec']['replicas'] == 0:
            # no need to check
            continue

        requested = deployment['status'].get('replicas', 0)
        updated = deployment['status'].get('updatedReplicas', 0)
        missing = deployment['status'].get('unavailableReplicas', 0)
        ready = deployment['status'].get('readyReplicas', 0)
        
        totals['requested'] += requested    
        totals['updated'] += updated
        totals['missing'] += missing
        totals['ready'] += ready


        if missing:
            del valid_deployments[full_name]
            broken_deployments[full_name] = \
                    '{}/{}'.format(missing, requested)

    output = []
    retv = 0
    if totals['missing']:
        output.append('WARNING - ')
        retv = 1 
        if len(broken_deployments) == 1:
             broken = broken_deployments.keys()[0]
             output.append('deployment {} is missing '.format(broken))
             if totals['missing'] == 1: 
                  output.append('one pod')
             else:
                  output.append('{} pods'.format(totals['missing']))
        else:
             output.append('{} deployments are missing {} pods'.format(
                   len(broken_deployments), totals['missing']))
    else:
       retv = 0
       output.append('All {} deployments are happy'.format(
                 len(valid_deployments)))
    output.append('|')
    for k in 'requested ready updated missing'.split():
         output.append('pods_{}={} '.format(k, totals[k]))
    total_deployments = len(valid_deployments)+len(broken_deployments)
    output.append('deployments_happy={};;;0;{} deployments_unhappy={};;;0;{}'.format(
            len(valid_deployments), total_deployments, 
            len(broken_deployments), total_deployments))
    print(''.join(output))
    if broken_deployments:
        print('')
        for k,v in broken_deployments.items():
            print('{} - {} missing'.format(k, v))
    raise SystemExit(retv)

if __name__ == '__main__':
    parse_arguments()
    main()
